// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/addons/fileUpload/dao/internal"
)

// internalAddonsFileUploadConfigDao is internal type for wrapping internal DAO implements.
type internalAddonsFileUploadConfigDao = *internal.AddonsFileUploadConfigDao

// addonsFileUploadConfigDao is the data access object for table addons_fileUpload_config.
// You can define custom methods on it to extend its functionality as you wish.
type addonsFileUploadConfigDao struct {
	internalAddonsFileUploadConfigDao
}

var (
	// AddonsFileUploadConfig is globally public accessible object for table addons_fileUpload_config operations.
	AddonsFileUploadConfig = addonsFileUploadConfigDao{
		internal.NewAddonsFileUploadConfigDao(),
	}
)

// Fill with you ideas below.
